path:
    root: ENCORE/
    scratch: scratch
    scripts: Scripts
    gtdbtk: [path/to/gtdbtk]
    mmnetwork_file: [path/to/mmnetworks.tsv]
    dda_file: [path/to/differential_abundance_analysis_results.tsv]
folder:
    logs: logs
    benchmarks: benchmarks
    quality: fastqc
    qfiltered: qfiltered
    assemblies: assemblies
    crossMap: crossMap 
    concoct: concoct
    maxbin: maxbin
    metabat: metabat
    refined: refined_bins
    reassembled: reassembled_bins
    classification: GTDBTk
    abundance: abundance
    proteinBins: protein_bins
    dnaBins: dna_bins
    GEMs: GEMs
    ecGEMs: ecGEMs
    stats: stats
    network: mmnetwork
    reporter: reporter_metabolite
DataforScripts:
    assemblyVis: DataforScripts/assemblyVis.R
    binningVis: DataforScripts/binningVis.R
    modelVis: DataforScripts/modelVis.R
    compositionVis: DataforScripts/compositionVis.R
    carveme: DataforScripts/media_db.tsv
    UniprotID: DataforScripts/UniprotID.txt
    kegg: DataforScripts/kegglist.txt
PythonScripts:
    kallisto2concoct: Scripts/PythonScripts/kallisto2concoct.py
    binFilter: Scripts/PythonScripts/binFilter.py
    adjust_coverage: Scripts/PythonScripts/adjust_coverage.py
MatlabScripts:
    createECGEM: Scripts/MATLABScripts/CreateECModel.m
    makeECGEM: Scripts/MATLABScripts/meta-gecko.m
    adaptertemplate: Scripts/MATLABScripts/adapterTemplate.m
Rscripts:
    assemblyVis: Scripts/RScripts/assemblyVis.R
    binningVis: Scripts/RScripts/binningVis.R
    modelVis: Scripts/RScripts/modelVis.R
    compositionVis: Scripts/RScripts/compositionVis.R
    taxonomy: Scripts/RScripts/taxonomy.R
    correctMetName: Scripts/RScripts/correctMetName.R
    identifyRM: Scripts/RScripts/identifyRM.R
    createMMNetwork: Scripts/RScripts/createMMNetwork.R
cores:
    fastp: 16 
    megahit: 64
    crossMap: 16
    concoct: 16
    metabat: 16
    maxbin: 16
    refine: 16
    reassemble: 64
    classify: 16
    gtdbtk: 16
    abundance: 16
    carveme: 16
    smetana: 16
    memote: 16
    grid: 16
    prokka: 16
    roary: 16
    diamond: 16
params:
    cutfasta: 10000
    assemblyPreset: meta-sensitive # can change to the meta-large later for faster testing speed, or set manually 
    assemblyMin: 1000
    concoct: 400
    concoctMinLength: 350
    metabatMin: 50000
    seed: 420
    minBin: 1500
    maxbinProb: 0.9
    maxbinMinLength: 1000
    maxbinIteration: 10
    refineMem: 1600
    refineComp: 50
    refineCont: 10
    reassembleMem: 1600
    reassembleComp: 50
    reassembleCont: 10
    carveMedia: M8
    smetanaMedia: M1,M2,M3,M4,M5,M7,M8,M9,M10,M11,M13,M14,M15A,M15B,M16
    smetanaSolver: CPLEX
    roaryI: 90
    roaryCD: 90
    FVAsensitivity: 0.95
envs:
    metagem: ENCORE/envs/metagem
    metawrap: ENCORE/envs/metawrap